// literally all the data from the previous model
const destinations = [
    { id: 1,  name: 'London',      country: 'United Kingdom', image: 'london.jpg' },
    { id: 2,  name: 'Paris',       country: 'France',         image: 'paris.jpg' },
    { id: 3,  name: 'Stockholm',   country: 'Sweden',         image: 'stockholm.jpg' },
    { id: 4,  name: 'Göteborg',  country: 'Sweden',         image: 'göteborg.jpg' },
    { id: 5,  name: 'Oslo',        country: 'Norway',         image: 'oslo.jpg' },
    { id: 6,  name: 'Copenhagen',  country: 'Denmark',        image: 'copenhagen.jpg' },
    { id: 7,  name: 'Örebro',      country: 'Sweden',         image: 'Örebro.jpg' },
    { id: 8,  name: 'Berlin',      country: 'Germany',        image: 'berlin.jpg' },
    { id: 9,  name: 'Helsinki',    country: 'Finland',        image: 'helsinki.jpg' },
    { id: 10, name: 'Prague',      country: 'Czech Republic', image: 'prag.jpg' },
    { id: 11, name: 'Malmö',       country: 'Sweden',         image: 'malmö.jpg' },
    { id: 12, name: 'Borås',       country: 'Sweden',         image: 'Borås.jpg' },
    { id: 13, name: 'Eskilstuna',  country: 'Sweden',         image: 'Eskillstuna.jpg' },
    { id: 14, name: 'Falun',       country: 'Sweden',         image: 'Falun.jpg' },
    { id: 15, name: 'Gävle',       country: 'Sweden',         image: 'Gävle.jpg' },
    { id: 16, name: 'Halmstad',    country: 'Sweden',         image: 'Halmstad.jpg' },
    { id: 17, name: 'Jönköping',   country: 'Sweden',         image: 'Jönköping.jpg' },
    { id: 18, name: 'Kalmar',      country: 'Sweden',         image: 'kalmar.jpg' },
    { id: 19, name: 'Karlskrona',  country: 'Sweden',         image: 'karlskrona.jpg' },
    { id: 20, name: 'Karlstad',    country: 'Sweden',         image: 'Karlstad.jpg' },
    { id: 21, name: 'Kiruna',      country: 'Sweden',         image: 'Kiruna.jpg' },
    { id: 22, name: 'Kristianstad',country: 'Sweden',         image: 'Krisianstad.jpg' },
    { id: 23, name: 'Linköping',   country: 'Sweden',         image: 'Linköping.jpg' },
    { id: 24, name: 'Luleå',       country: 'Sweden',         image: 'Luleå.jpg' },
    { id: 25, name: 'Lund',        country: 'Sweden',         image: 'Lund.jpg' },
    { id: 26, name: 'Mora',        country: 'Sweden',         image: 'Mora.jpg' },
    { id: 27, name: 'Narvik',      country: 'Norway',         image: 'Narvik.jpg' },
    { id: 28, name: 'Norrköping',  country: 'Sweden',         image: 'Norrköping.jpg' },
    { id: 29, name: 'Skövde',      country: 'Sweden',         image: 'skövde.jpg' },
    { id: 30, name: 'Strömstad',   country: 'Sweden',         image: 'strömstad.jpg' },
    { id: 31, name: 'Sundsvall',   country: 'Sweden',         image: 'sundsvall.jpg' },
    { id: 32, name: 'Trollhättan', country: 'Sweden',         image: 'Trollhättan.jpg' },
    { id: 33, name: 'Uddevalla',   country: 'Sweden',         image: 'Udervalla.jpg' },
    { id: 34, name: 'Umeå',        country: 'Sweden',         image: 'umeå.jpg' },
    { id: 35, name: 'Uppsala',     country: 'Sweden',         image: 'uppsala.jpg' },
    { id: 36, name: 'Västerås',    country: 'Sweden',         image: 'västerås.jpg' },
    { id: 37, name: 'Visby',       country: 'Sweden',         image: 'visby.jpg' },
    { id: 38, name: 'Växjö',       country: 'Sweden',         image: 'växjö.jpg' },
    { id: 39, name: 'Östersund',   country: 'Sweden',         image: 'östersund.jpg' },
    { id: 40, name: 'Alvesta',     country: 'Sweden',         image: 'Alvesta.jpg' },
    { id: 41, name: 'Bromma',      country: 'Sweden',         image: 'Bromma.jpg' },
];

export default destinations;